runtime: java11

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
handlers:
  - url: /.*
    script: this field is required, but ignored
automatic_scaling:
  target_cpu_utilization: 0.5
  max_instances: 5