runtime: java11
instance_class: B2

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,mysql"
handlers:
  - url: /.*
    script: this field is required, but ignored
automatic_scaling:
  target_cpu_utilization: 0.95
  max_instances: 10